Style/Documentation:
  Enabled: false

Security/Eval:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/lib/utils/matrix_spec.rb"
